#!/bin/bash

host='hostname'
if [ "$host"="server" ]; then
sudo apt-get install nfs-kernel-server nfs-common portmap -y
sudo mkdir /home/nfs
sudo chown nobody:nogroup /home/nfs
sudo nano /etc/exports
#/home/nfs 192.168.0.109(rw,sync,no_root_squash,no_subtree_check)

#share
sudo exportfs -a
sudo systemctl enable nfs-server
sudo mount -t nfs 192.168.0.109:/home/nfs /mnt/nfs

echo "server located"

elif [ "$host"="client" ]; then

sudo apt-get install nfs-common

echo "client located"

else 
echo "Faild to find hostname"
fi 
